# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baidu_hanyu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiduHanyu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hz', models.CharField(max_length=32, verbose_name='汉字')),
                ('py', models.CharField(max_length=32, verbose_name='拼音')),
            ],
            options={
                'db_table': 'baidu_hanyu',
            },
        ),
        migrations.DeleteModel(
            name='Baidu_hanyu',
        ),
    ]
